### ISSUE TITLE
Model export fails on transformation pickle

### ISSUE THREAD

**Issue by hellno** [rbracco/fastai2_audio#39]
Hi,

I'm trying to export a trained model, but it fails when trying to pickle the transformations.
I was wondering if this functionality is supported in fastai2_audio, because I used only out-of-the box methods.

How to reproduce:
Run this in the end of a training notebook
```python
learn.export('model_fname')
``` 

The error message:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-125-7815b0949909> in <module>
----> 1 learner.export('model_fname')

/usr/local/lib/python3.7/site-packages/torch/serialization.py in save(obj, f, pickle_module, pickle_protocol, _use_new_zipfile_serialization)
    369     with _open_file_like(f, 'wb') as opened_file:
--> 370         _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
    371 

/usr/local/lib/python3.7/site-packages/torch/serialization.py in _legacy_save(obj, f, pickle_module, pickle_protocol)
    441     pickler = pickle_module.Pickler(f, protocol=pickle_protocol)
    442     pickler.persistent_id = persistent_id
--> 443     pickler.dump(obj)

AttributeError: Can't pickle local object 'CropSignal.<locals>._inner'
```

What I tried:
- run my custom training notebook: fails
- copy Google Colab example notebook with my data: fails
- move transformation definition from common function to list: still fails
- explicitly only import transformations that I use from `fastai2_audio.augment`: fails, no change
- google 😅

These are the transformations I tried to use, taken from the tutorials in this project.
```python
item_tfms = [
    RemoveSilence(), 
    CropSignal(3000), 
    DownmixMono(),
    Resample(22050), 
    AddNoise(noise_level=0.1), 
    AudioToMFCC(n_mffc=20, melkwargs={"n_fft":2048, "hop_length":256, "n_mels":128}),
    Delta(),
]
```

1. Is this a known problem? If yes, is there a workaround?
2. Do you have a hint how to fix this? I'm up for trying and opening a PR

**Comment by mogwai** [comment]
Testing whether a model can be exported hasn't been tested thoroughly but is a feature that we would like to support. If you work out what the issue is then please yes open a PR.

**Comment by scart97** [comment]
When exporting a Learner in fastai2, it also tries to export the dataloaders. The problem is that our current way of writing the data augmentation functions is not compatible with pickle (see [this](https://stackoverflow.com/questions/12019961/python-pickling-nested-functions) to know more why). But, we can change the code to subclass `Transform` without changing the user interface. I started working on the fix, but it will take a couple of days to translate all the code and properly test it.

**Comment by hellno** [comment]
Thanks a lot @scart97 
Let me know if I can help or support in any way

**Comment by scart97** [comment]
@hellno  as a workaround you can export only the model, as it's just a normal nn.Module. Following [the guide](https://pytorch.org/tutorials/beginner/saving_loading_models.html), `torch.save(learn.model.state_dict(), PATH)`, and to load it you create a new learner the same way you created the first time and try to run `learn.model.load_state_dict(torch.load(PATH))`.

**Comment by hellno** [comment]
this works now with the changes in #41 😍 thank you!
