### ISSUE TITLE
DownmixMono examples not working in 01_augement notebook

### ISSUE THREAD

**Issue by jdiedrick** [rbracco/fastai2_audio#6]

**Comment by rbracco** [comment]
Thanks for reporting. Broken for the same reason as [Issue 5](https://github.com/rbracco/fastai2_audio/issues/5). The fake multichannel data had been transformed in place and not reinitialized before attempting to downmix to mono. Quick fix is including the line `fake_multichannel = _audio_mc_ex()` before the DownmixMono transform. This will be in next PR
