### ISSUE TITLE
ImportError: cannot import name 'progress_bar' 

### ISSUE THREAD

**Issue by jdiedrick** [rbracco/fastai2_audio#7]
In 02_tutorial notebook:
```
from fastprogress import progress_bar as pb

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-34-383e3a70bf7e> in <module>
----> 1 from fastprogress import progress_bar as pb

ImportError: cannot import name 'progress_bar' from 'fastprogress' (/home/paperspace/anaconda3/envs/fastai2/lib/python3.7/site-packages/fastprogress/__init__.py)
```

**Comment by rbracco** [comment]
I couldn't replicate this issue. I am running the latest version of fastprogress 0.1.22. Are you still having this problem? Can you provide more detail? Thank you!

**Comment by scart97** [comment]
This error is related to [this](https://forums.fast.ai/t/fastai-v2-audio/53535/52) post at the forums, and happen because the conda install from out environment.yml was not respecting fastai2 dependencies.

**Comment by jdiedrick** [comment]
@scart97 Yeah I'm still getting the error for now. I see you have a PR out with a possible fix, but that PR is failing in CI. For now I can do a manual fix on my end.
